### ISSUE TITLE
Some errors when using ScanNet

### ISSUE THREAD

**Issue by BIT-DYN** [Willyzw/HI-SLAM2#3]
Thank you for the excellent work and well-organized code!

I successfully ran the code on the Replica dataset. 

However, when attempting to use the ScanNet dataset, I encountered the following error.

I am using scene0000_00 without modifying any configurations. Do you have any insights into what might be causing this issue?

> Traceback (most recent call last):
  File "/code1/dyn/codes/OpenWorld/OpenGS/HI-SLAM2/demo.py", line 121, in <module>
    hi2.track(t, image, intrinsics=intrinsics, is_last=is_last)
  File "/code1/dyn/codes/OpenWorld/OpenGS/HI-SLAM2/hislam2/hi2.py", line 103, in track
    self.call_gs(viz_idx)
  File "/code1/dyn/codes/OpenWorld/OpenGS/HI-SLAM2/hislam2/hi2.py", line 83, in call_gs
    self.gs.process_track_data(data)
  File "/code1/dyn/codes/OpenWorld/OpenGS/HI-SLAM2/hislam2/gs_backend.py", line 113, in process_track_data
    self.add_next_kf(idx, viewpoint, depth_map=packet["depths"][i].numpy())
  File "/code1/dyn/codes/OpenWorld/OpenGS/HI-SLAM2/hislam2/gs_backend.py", line 153, in add_next_kf
    self.gaussians.extend_from_pcd_seq(
  File "/code1/dyn/codes/OpenWorld/OpenGS/HI-SLAM2/hislam2/gaussian/scene/gaussian_model.py", line 221, in extend_from_pcd_seq
    self.extend_from_pcd(
  File "/code1/dyn/codes/OpenWorld/OpenGS/HI-SLAM2/hislam2/gaussian/scene/gaussian_model.py", line 204, in extend_from_pcd
    self.densification_postfix(
  File "/code1/dyn/codes/OpenWorld/OpenGS/HI-SLAM2/hislam2/gaussian/scene/gaussian_model.py", line 458, in densification_postfix
    optimizable_tensors = self.cat_tensors_to_optimizer(d)
  File "/code1/dyn/codes/OpenWorld/OpenGS/HI-SLAM2/hislam2/gaussian/scene/gaussian_model.py", line 411, in cat_tensors_to_optimizer
    stored_state["exp_avg"] = torch.cat(
RuntimeError: CUDA error: invalid configuration argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Willyzw** [comment]
Sorry to hear about the issue. At first glance, it seems like the error might be related to densification, possibly caused by NaNs or zero-length tensors that can’t be concatenated. maybe due to incorrect tracking data. Did you maybe use the `preprocess_scannet.py` to prepare data? For better understanding could you rerun the code with the CUDA_LAUNCH_BLOCKING=1 prefix to confirm if the error actually occurs at the reported line. Additionally, it would to helpful to inspect the tensors using the following code snippet to check for anomalies in `densification_postfix` function
```
for k, v in d.items():
    print(k, v.shape, torch.isnan(v).any(), torch.isinf(v).any())
```
This should provide more insights wht is going wrong

**Comment by Willyzw** [comment]
As no further response, I assume the issue can be considered resolved and will close it
