### ISSUE TITLE
multiprocessing problem

### ISSUE THREAD

**Issue by HeSongy** [Willyzw/HI-SLAM2#4]
The problem  running my own dataset
```
Processing keyframe 11 gs 0:  90%|██████████████████████████████████████████████████████████████████████████████████████▊         | 19/21 [01:05<00:01,  1.43it/s]
GSBackend: Initialized map
Processing keyframe 12 gs 80656:  95%|███████████████████████████████████████████████████████████████████████████████████████▌    | 20/21 [01:31<00:00,  1.43it/s]
Traceback (most recent call last):
  File "/home/cver/code/HI-SLAM2/demo.py", line 113, in <module>
    (t, image, intrinsics, is_last) = queue.get()
                                      ^^^^^^^^^^^
  File "/home/cver/miniconda3/envs/hislam2/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cver/miniconda3/envs/hislam2/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", line 355, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "/home/cver/miniconda3/envs/hislam2/lib/python3.11/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cver/miniconda3/envs/hislam2/lib/python3.11/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cver/miniconda3/envs/hislam2/lib/python3.11/multiprocessing/connection.py", line 519, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cver/miniconda3/envs/hislam2/lib/python3.11/multiprocessing/connection.py", line 647, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by stan1512** [comment]
I had the same problem today and I'm looking for a solution too

**Comment by Willyzw** [comment]
Sorry to hear abou the issue, I haven't encountered this before. But based on the error message, it seems that the tensor put in the multiprocessing queue was not handled properly. This discussion https://github.com/pytorch/pytorch/issues/60654#issuecomment-869717867 suggests to convert the tensor to numpy array before putting into the queue and convert back to tensor after retrieving it. you might give this a try, hope it resolves the issue!

**Comment by HeSongy** [comment]
> Sorry to hear abou the issue, I haven't encountered this before. But based on the error message, it seems that the tensor put in the multiprocessing queue was not handled properly. This discussion [pytorch/pytorch#60654 (comment)](https://github.com/pytorch/pytorch/issues/60654#issuecomment-869717867) suggests to convert the tensor to numpy array before putting into the queue and convert back to tensor after retrieving it. you might give this a try, hope it resolves the issue!

This method solved the problem


`queue.put()` : 
```
        # queue.put((t, image[None], intrinsics[None], is_last))
        queue.put((t, image[None].numpy(), intrinsics[None].numpy(), is_last))
  ```

`queue.get()`:
```
        (t, image, intrinsics, is_last) = queue.get()
        image = torch.tensor(image)
        intrinsics = torch.tensor(intrinsics)
```

**Comment by kk6398** [comment]
> > Sorry to hear abou the issue, I haven't encountered this before. But based on the error message, it seems that the tensor put in the multiprocessing queue was not handled properly. This discussion [pytorch/pytorch#60654 (comment)](https://github.com/pytorch/pytorch/issues/60654#issuecomment-869717867) suggests to convert the tensor to numpy array before putting into the queue and convert back to tensor after retrieving it. you might give this a try, hope it resolves the issue!
> 
> This method solved the problem, Thanks!
> 
> convert the tensor to numpy array before putting into the queue: `queue.put()` :
> 
> ```
>         # queue.put((t, image[None], intrinsics[None], is_last))
>         queue.put((t, image[None].numpy(), intrinsics[None].numpy(), is_last))
> ```
> 
> convert back to tensor after retrieving `queue.get()`:
> 
> ```
>         (t, image, intrinsics, is_last) = queue.get()
>         image = torch.tensor(image)
>         intrinsics = torch.tensor(intrinsics)
> ```

Sorry, I try to use the code, both  of "queue.put()" and "queue.get()" simoutanously , that you mentioned both .  Although finishing the process and print "Done", however, after that,  it still occurs the same bug:
![image](https://github.com/user-attachments/assets/d0e8aff3-fb9f-481d-86d3-e47730c83976)

**Comment by Willyzw** [comment]
> > > Sorry to hear abou the issue, I haven't encountered this before. But based on the error message, it seems that the tensor put in the multiprocessing queue was not handled properly. This discussion [pytorch/pytorch#60654 (comment)](https://github.com/pytorch/pytorch/issues/60654#issuecomment-869717867) suggests to convert the tensor to numpy array before putting into the queue and convert back to tensor after retrieving it. you might give this a try, hope it resolves the issue!
> > 
> > 
> > This method solved the problem, Thanks!
> > convert the tensor to numpy array before putting into the queue: `queue.put()` :
> > ```
> >         # queue.put((t, image[None], intrinsics[None], is_last))
> >         queue.put((t, image[None].numpy(), intrinsics[None].numpy(), is_last))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > convert back to tensor after retrieving `queue.get()`:
> > ```
> >         (t, image, intrinsics, is_last) = queue.get()
> >         image = torch.tensor(image)
> >         intrinsics = torch.tensor(intrinsics)
> > ```
> 
> Sorry, I try to use the code, both of "queue.put()" and "queue.get()" simoutanously , that you mentioned both . Although finishing the process and print "Done", however, after that, it still occurs the same bug: ![image](https://private-user-images.githubusercontent.com/70420660/401052469-d0e8aff3-fb9f-481d-86d3-e47730c83976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3ODA3NjcsIm5iZiI6MTczNjc4MDQ2NywicGF0aCI6Ii83MDQyMDY2MC80MDEwNTI0NjktZDBlOGFmZjMtZmI5Zi00ODFkLTg2ZDMtZTQ3NzMwYzgzOTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDE1MDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OTcxZWNmOTEyY2YyNGVhZWZjNTdmMjY1YTUzYWEwMDVjOWU1YjJmNTU5YmExODAxNWU2OGY0YzQzOTljYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.prpboasffLTCi-QgeQwhH631syHY6hD4GDOliAhP2Bc)

It seems the process had completed successfully, as the evaluation was performed and the results were printed. The error message appears to be related to the GUI and typically shows up after pressing Ctrl+C. I believe it can be safely ignored.
